project:
  type: website
  output-dir: docs
  
website:
  title: "Todd Stuebing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/awk1972/Quart_Website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Todd Stuebing"

format:
  html:
    theme: United
    toc: true

editor: source

